name = "red-bridge-consultation-api"
main = "worker.js"
compatibility_date = "2024-03-04"

# Do not commit secrets to this file. 
# Secrets (ZOHO_CLIENT_ID, etc.) are set via 'wrangler secret put'

[routes]
# This routes requests from your domain to this worker
pattern = "www.redbridgesolutions.io/api/submit-consultation"
custom_domain = true